/* eslint-disable */
/**
 * Generated `api` utility. Regenerated by `npx convex dev`.
 */
import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as users from "../users.js";

declare const fullApi: ApiFromModules<{
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
